# -*- coding: utf-8 -*-
"""Titanic Machine Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nxGO4QBi3btNnHPx0CICsFL3Dvl7nBPE
"""

import numpy as np 
import pandas as pd 
import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

import plotly.graph_objects as go
import plotly.offline as po
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import matplotlib as plt
import plotly.express as px
import random
import plotly.figure_factory as ff

test = pd.read_csv("/content/test.csv")
test.head(10)

train=pd.read_csv("/content/train.csv")
train.head(10)

women=train.loc[train.Sex=="female"]["Survived"]
women_percent=sum(women)*100/len(women)
print("% of women who survived is", women_percent)
men=train.loc[train.Sex=="male"]["Survived"]
men_percent=sum(men)*100/len(men)
print("% of men who survived is", men_percent)

from sklearn.ensemble import RandomForestClassifier
y = train["Survived"]
features = ["Pclass", "Sex", "SibSp", "Parch"]
X = pd.get_dummies(train[features])
X_test = pd.get_dummies(test[features])
model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X, y)
predictions = model.predict(X_test)
output = pd.DataFrame({'PassengerId': test.PassengerId, 'Survived': predictions})
output.to_csv('result.csv', index=False)